# -*- coding: utf-8 -*-
"""Klasifikasi dengan Naive Bayes .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sVQXAOdoii_8MZYP0I4ksTeOXVYYB3CG
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

from google.colab import files
uploaded = files.upload()

import io
data = pd.read_csv(io.BytesIO(uploaded['diabetes.csv']))

X = data.drop(columns=['Outcome'])
y = data['Outcome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

nb_model = GaussianNB()

nb_model.fit(X_train, y_train)

y_pred = nb_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Akurasi Model: {accuracy * 100:.2f}%")

classification_rep = classification_report(y_test, y_pred)
print("Laporan Klasifikasi:")
print(classification_rep)